spring:
  datasource:
    hikari:
      username: ODDI_APP
      password: "app21_oddiXX"
      pool-name: oddiad-pool
      max-lifetime: 12000
      connection-test-query: select now()
      minimum-idle: 2
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: "jdbc:mysql://rds-an2-oddiad-dev-mysql.ca3pv7invojs.ap-northeast-2.rds.amazonaws.com:3310/oddi?characterEncoding=utf8&useSSL=false"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults=false: false
logging:
  config: classpath:logback-file.xml

# timezone
timezone: "Asia/Seoul"

# two factor type
twofactor:
  type: "SMS"

token:
  expired-min: 60
