spring:
  datasource:
    hikari:
      username: oddi
      password: "oddi1@#"
      pool-name: oddiad-pool
      max-lifetime: 12000
      connection-test-query: select now()
      minimum-idle: 10
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: "jdbc:log4jdbc:mysql://ls-a2834d111b7d0d1385ca4360b6718cf409b75eff.cvxedmimklz0.ap-northeast-2.rds.amazonaws.com:3306/oddi_ad"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults=false: false
logging:
  config: classpath:logback-dev.xml

# timezone
timezone: "Asia/Seoul"

# two factor type
twofactor:
  type: "SMS"

token:
  expired-min: 60
